#!/usr/bin/env bash

sudo apt-get update

sudo apt-get install -y nginx

sudo bash -c "cat > /etc/nginx/sites-available/default" <<EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        add_header X-Served-By \$(hostname);
        # Additional Nginx configuration if needed
    }
}
EOL

sudo systemctl reload nginx


echo "Configuration completed."
