#!/usr/bin/env bash
#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

echo -e "Updates the package information and upgrades existing packages on the system\n"
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

echo -e "Appends the HAProxy configuration to /etc/haproxy/haproxy.cfg.\n"
sudo echo "\
frontend Xs55kh
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server web-01 54.90.30.64:80
    server web-02 52.90.15.99:80
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy restart

echo -e "\ncompleted\n"
