#!/usr/bin/env bash
#Bash script that loops from 1 to 10 and

i=1
while [ "$i" -lt 11 ]
do
	if [ "$i" -eq 4 ]
	then
		echo "bad luck"
		((i++))
		continue
	elif [ "$i" -eq 8 ]
	then
		echo "good luck"
		((i++))
		continue
	else
        	echo "Best School"
        	((i++))
	fi
done
