#!/usr/bin/env bash
#Bash script that gives you information about the school file.

filename="school"

if [ -e "$filename" ]
then
	echo "school file exists"
	
	if [ -f "$filename" ]
	then
		content="$(cat "$filename")"
		
		if [ -z "$content" ]
		then
			echo "school file is empty"
		else
			echo "school file is not empty"
		fi
		 echo "school is a regular file"
	else
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
