#!/usr/bin/env bash
#Bash script that configures an Ubuntu server

cp /etc/hosts ~/hosts_file.new

sed -i "s/^127[0-9.]*\slocalhost/127.0.0.2 localhost/" ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new

cp -f ~/hosts_file.new /etc/hosts

