#!/usr/bin/env bash
#Run nginx as a nginx and fix server bug
chmod 644 /etc/nginx/nginx.conf
sudo sed -Ei '1s/.*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
